# coding: utf-8

# flake8: noqa
"""
    Job Portal API

    REST API for job listings and applications

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from openapi_client.models.application_create import ApplicationCreate
from openapi_client.models.application_response import ApplicationResponse
from openapi_client.models.http_validation_error import HTTPValidationError
from openapi_client.models.job_create import JobCreate
from openapi_client.models.job_response import JobResponse
from openapi_client.models.location_inner import LocationInner
from openapi_client.models.validation_error import ValidationError

