# coding: utf-8

"""
    Job Portal API

    REST API for job listings and applications

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_apply_for_job_jobs_id_apply_post(self) -> None:
        """Test case for apply_for_job_jobs_id_apply_post

        Apply For Job
        """
        pass

    def test_create_job_jobs_post(self) -> None:
        """Test case for create_job_jobs_post

        Create Job
        """
        pass

    def test_list_jobs_jobs_get(self) -> None:
        """Test case for list_jobs_jobs_get

        List Jobs
        """
        pass


if __name__ == '__main__':
    unittest.main()
